name: Trigger auto deployment for aca-stress-ui

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aca-stress-ui-AutoDeployTrigger-69920d6c-b3cb-467d-bd3a-b5b53ef3612c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ACASTRESSUI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACASTRESSUI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACASTRESSUI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: haoacr.azurecr.io
          registryUsername: ${{ secrets.ACASTRESSUI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACASTRESSUI_REGISTRY_PASSWORD }}
          containerAppName: aca-stress-ui
          resourceGroup: hao-ACA-test
          imageToBuild: haoacr.azurecr.io/aca-stress-ui:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


