name: Trigger auto deployment for hao-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/hao-container-app-AutoDeployTrigger-cc3e00c8-bb47-46fe-a9db-60bbe3ed4dbd.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.HAOCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HAOCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HAOCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerappjobtest.azurecr.io
          registryUsername: ${{ secrets.HAOCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HAOCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: hao-container-app
          resourceGroup: ContainerApp
          imageToBuild: containerappjobtest.azurecr.io/hao-container-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


