name: Trigger auto deployment for hao-aca-js-sample

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/hao-aca-js-sample-AutoDeployTrigger-83035c42-faad-4532-b703-2c5536efebfc.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.HAOACAJSSAMPLE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HAOACAJSSAMPLE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HAOACAJSSAMPLE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: haoacr.azurecr.io
          registryUsername: ${{ secrets.HAOACAJSSAMPLE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HAOACAJSSAMPLE_REGISTRY_PASSWORD }}
          containerAppName: hao-aca-js-sample
          resourceGroup: hao-ACA-test
          imageToBuild: haoacr.azurecr.io/hao-aca-js-sample:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


