name: Trigger auto deployment for hao-aca-js-sample

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/hao-aca-js-sample-AutoDeployTrigger-5a6a5660-1c83-4b19-87c2-7ddc63a5db6c.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.HAOACAJSSAMPLE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: haoacr.azurecr.io
          registryUsername: ${{ secrets.HAOACAJSSAMPLE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HAOACAJSSAMPLE_REGISTRY_PASSWORD }}
          containerAppName: hao-aca-js-sample
          resourceGroup: hao-ACA-test
          imageToBuild: haoacr.azurecr.io/hao-aca-js-sample:${{ github.sha }}
          
            

     

